name: Spear Core Database Setup
description: A GitHub action to pull mysqldump files from S3 and import them.
branding:
  icon: check-circle
  color: green
runs:
  using: docker
  image: Dockerfile
  post-if: inputs.base_ref != ""
  post-entrypoint: 'post-entrypoint.sh'
inputs:
  databases:
    description: Space-delimited list of databases
    required: true
  s3_bucket:
    description: The S3 bucket
    required: true
  base_ref:
    description: The target branch to use for schema lookups
    required: false
  mysql_host:
    description: MySQL Host
    required: false
    default: mysql_tdd
  mysql_user:
    description: MySQL User
    required: false
    default: root
  mysql_pass:
    description: MySQL Pass
    required: false
  mysql_port:
    description: MySQL Port
    required: false
    default: "3306"
