name: Spear Core Database Setup
description: A GitHub action to pull mysqldump files from S3 and import them.
branding:
  icon: check-circle
  color: green
runs:
  using: docker
  image: Dockerfile
inputs:
  s3_bucket:
    description: The S3 Bucket
    required: true
  databases:
    description: Space-delimited list of databases
    required: true
  mysql_host:
    description: MySQL Host
    required: false
    default: mysql_tdd
  mysql_user:
    description: MySQL User
    required: false
    default: root
  mysql_pass:
    description: MySQL Pass
    required: false
  mysql_port:
    description: MySQL Port
    required: false
    default: "3306"
